# syntax=docker/dockerfile:1

# Bad practice to use mutable tag
# Docker Ubuntu LTS image
FROM docker.io/library/ubuntu@sha256:3afff29dffbc200d202546dc6c4f614edc3b109691e7ab4aa23d02b42ba86790

USER root

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
  git \
  software-properties-common \
#   python3 \
#   python3-pip \
  curl \
  nginx \
  && rm -rf /var/lib/apt/lists/*

# https://askubuntu.com/questions/682869/how-do-i-install-a-different-python-version-using-apt-get
RUN add-apt-repository ppa:deadsnakes/ppa 
RUN apt-get install -y --no-install-recommends python3.11 python3-pip python3.11-venv
RUN python3 -m venv .venv
RUN . .venv/bin/activate
RUN python3 -m pip install --upgrade pip

# Remove bash permissions from executables
RUN find / -perm +6000 -type f -exec chmod a-s {} \; || true 

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.cache/pip to speed up subsequent builds.
# Leverage a bind mount to requirements.txt to avoid having to copy them into
# into this layer.
RUN python3 -m pip install -r requirements.txt

# Copy the source code into the container.
COPY . .

# Expose the port that the application listens on.
EXPOSE 8000

# Run the application.
# CMD uvicorn 'app:app' --host=0.0.0.0 --port=8000
CMD ["/usr/bin/sh","start-app.sh"]
